### ISSUE TITLE
larql fcl par holdover

### ISSUE THREAD

**Issue by calcuttj** [DUNE/duneprototypes#27]
https://github.com/DUNE/duneprototypes/blob/develop/duneprototypes/Coldbox/vd/fcl/services_vdcoldbox.fcl#L113 is causing an issue in [ci_detsim_regression_test_dunefd]( https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/build_detail/phase_details?build_id=dune_ci/15810&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

Not sure why it's breaking now. Earlier CI tests were working. I think this just needs to be replaced with 
`@local::dunefd_ionandscint` but I defer to experts

**Comment by lpaulucc** [comment]
Yes, you need to use `@local::dunefd_ionandscint`
and change this parameter in larg4parameters to get LArQL working
` services.LArG4Parameters.UseModLarqlRecomb: true
`

**Comment by calcuttj** [comment]
Will change accordingly
