### ISSUE TITLE
Lar options to skip and specify nproc fail with HD coldbox data

### ISSUE THREAD

**Issue by dladams** [DUNE/duneprototypes#8]
I see that the lar options to skip event ans process only a specified number of events fail when we read HD coldbox data, e.g.
even with "-n 1 -nskip 4" on the lar command line, all events are processed.

**Comment by dladams** [comment]
Tom,

I think this is a known issue and something we do not plan to fix. Is this correct?

Thanks.

**Comment by tomjunk** [comment]
We are now on art v3_12_00.  Should work now.  Closing
